server:
  port: 9000

spring:
  application:
    name: alibaba-math-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:18080
      filter:
        url-patterns: /sentinel/**
      log:
        dir: logs

management:
  endpoints:
    web:
      exposure:
        include: '*'